{% set data = load_setup_py_data(from_recipe_dir=True) %}

package:
  name: {{ data.get('name') }}
  version: {{ data.get('version') }}

source:
  path: .

build:
  number: {{ data.get('version') }}
  script: python3 setup.py install

requirements:
  host:
    - python
  run:
    - python
